import {
  PenTool,
  Languages,
  ScanText,
  FileText,
  Mic,
  Volume2,
  GraduationCap,
  Share2,
  Wand2,
} from 'lucide-react';
import { ToolMeta, ToolId } from './types';

export const TOOL_CATEGORIES = [
  'Writing',
  'Language',
  'Vision & Docs',
  'Audio & Voice',
  'Education & Media',
];

export const AI_TOOLS: ToolMeta[] = [
  {
    id: 'text-writer',
    name: 'AI Text Writer',
    nameUrdu: 'اے آئی ٹیکسٹ رائٹر',
    nameHindi: 'एआई टेक्स्ट राइटर',
    nameArabic: 'كاتب النصوص الذكي',
    category: 'Writing',
    description: 'Generate emails, messages, social media posts, captions, descriptions, and blogs.',
    icon: PenTool,
    color: 'text-indigo-400',
    bgColor: 'bg-indigo-500/15',
    tags: ['Email', 'Message', 'Blog', 'Caption'],
    badge: 'Popular',
    popular: true,
  },
  {
    id: 'translator',
    name: 'AI Translator',
    nameUrdu: 'اے آئی مترجم',
    nameHindi: 'एआई अनुवादक',
    nameArabic: 'المترجم الذكي الفوري',
    category: 'Language',
    description: 'Instant translation between English, Urdu, Hindi, Arabic and 50+ languages with auto-detection.',
    icon: Languages,
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-500/15',
    tags: ['English', 'Urdu', 'Hindi', 'Arabic'],
    badge: 'Auto Detect',
    popular: true,
  },
  {
    id: 'photo-to-text',
    name: 'Photo to Text (OCR)',
    nameUrdu: 'تصویر سے ٹیکسٹ (او سی آر)',
    nameHindi: 'फोटो से टेक्स्ट (ओसीआर)',
    nameArabic: 'استخراج النص من الصور',
    category: 'Vision & Docs',
    description: 'Capture or upload photo, instantly extract text with high-precision OCR, edit and export.',
    icon: ScanText,
    color: 'text-emerald-400',
    bgColor: 'bg-emerald-500/15',
    tags: ['OCR', 'Camera', 'Receipt', 'Document'],
    badge: 'Vision AI',
    popular: true,
  },
  {
    id: 'pdf-tools',
    name: 'PDF AI Tools',
    nameUrdu: 'پی ڈی ایف اے آئی ٹولز',
    nameHindi: 'पीडीएफ एआई टूल्स',
    nameArabic: 'أدوات مستندات PDF',
    category: 'Vision & Docs',
    description: 'Upload PDF, get executive summaries, ask questions interactively, and download insights.',
    icon: FileText,
    color: 'text-rose-400',
    bgColor: 'bg-rose-500/15',
    tags: ['PDF', 'Summary', 'Q&A Chat', 'Reports'],
    badge: 'Smart Doc',
    popular: true,
  },
  {
    id: 'voice-to-text',
    name: 'Voice to Text',
    nameUrdu: 'آواز سے ٹیکسٹ کنورٹر',
    nameHindi: 'आवाज से टेक्स्ट',
    nameArabic: 'تحويل الصوت إلى نص',
    category: 'Audio & Voice',
    description: 'Record speech and convert to accurate text in English, Urdu, Hindi, Arabic with waveform.',
    icon: Mic,
    color: 'text-violet-400',
    bgColor: 'bg-violet-500/15',
    tags: ['Speech', 'Microphone', 'Audio', 'Dictation'],
    popular: false,
  },
  {
    id: 'text-to-speech',
    name: 'Text to Speech Studio',
    nameUrdu: 'ٹیکسٹ سے آواز (ٹی ٹی ایس)',
    nameHindi: 'टेक्स्ट से आवाज (टीटीएस)',
    nameArabic: 'تحويل النص إلى كلام',
    category: 'Audio & Voice',
    description: 'Natural AI voice reading with speed/pitch controls and instant WAV audio download.',
    icon: Volume2,
    color: 'text-pink-400',
    bgColor: 'bg-pink-500/15',
    tags: ['Voice', 'TTS', 'Audio Download', 'Natural'],
    popular: false,
  },
  {
    id: 'study-helper',
    name: 'AI Study Helper',
    nameUrdu: 'اے آئی اسٹڈی ہیلپر',
    nameHindi: 'एआई स्टडी हेल्पर',
    nameArabic: 'المساعد الدراسي الذكي',
    category: 'Education & Media',
    description: 'Simple concept explanations, revision notes, and interactive quizzes with instant scores.',
    icon: GraduationCap,
    color: 'text-amber-400',
    bgColor: 'bg-amber-500/15',
    tags: ['Quiz', 'Flashcards', 'Explanations', 'Exams'],
    badge: 'Students',
    popular: true,
  },
  {
    id: 'social-assistant',
    name: 'Social Media Assistant',
    nameUrdu: 'سوشل میڈیا اسسٹنٹ',
    nameHindi: 'सोशल मीडिया असिस्टेंट',
    nameArabic: 'مساعد وسائل التواصل',
    category: 'Education & Media',
    description: 'Captions, hashtags, hooks, and video descriptions for Instagram, TikTok, YouTube & Facebook.',
    icon: Share2,
    color: 'text-purple-400',
    bgColor: 'bg-purple-500/15',
    tags: ['Instagram', 'TikTok', 'YouTube', 'Hashtags'],
    badge: 'Viral AI',
    popular: true,
  },
  {
    id: 'photo-enhancer',
    name: 'AI Photo Enhancer',
    nameUrdu: 'اے آئی فوٹو اینہانسر',
    nameHindi: 'एआई फोटो एन्हांसर',
    nameArabic: 'محسن الصور الذكي',
    category: 'Vision & Docs',
    description: 'Upscale resolution, sharpen blurry images, and compare with interactive Before/After slider.',
    icon: Wand2,
    color: 'text-teal-400',
    bgColor: 'bg-teal-500/15',
    tags: ['Super-Res', 'Before/After', 'Sharpen', 'HD'],
    badge: 'HD Pro',
    popular: true,
  },
];

export function getToolById(id: ToolId): ToolMeta | undefined {
  return AI_TOOLS.find((t) => t.id === id);
}
